id: P007881
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16208
  title: ཆོས་འབྱུང་ཀུན་བཏུས་པདྨ་དཀར་པོའི་ཆུན་པོ་བློ་གསལ་འདྲེན་བྱེད་བདུད་རྩིའི་དཔལ་ཡོན།
  author: ''
  volumes:
    e4d172ba3af6496585ed2cecac1cb177:
      image_group_id: I1KG16237
      title: ''
      volume_number: 1
      total_pages: 238
ebook_metadata:
  title: ཆོས་འབྱུང་ཀུན་བཏུས་པདྨ་དཀར་པོའི་ཆུན་པོ་བློ་གསལ་འདྲེན་བྱེད་བདུད་རྩིའི་དཔལ་ཡོན།
  author: ''
  sku: P007881
  cover: cover.jpg
  layers:
  - pagination
